import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { getUserProfile, saveUserProfile } from "@/lib/storage";
import { useColors } from "@/hooks/use-colors";

export default function EditProfileScreen() {
  const colors = useColors(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [goal, setGoal] = useState("Definir abdômen"); const [level, setLevel] = useState("Iniciante"); const [availableTime, setAvailableTime] = useState("20 min");
  useEffect(() => { getUserProfile().then((p) => { if (p) { setName(p.name); setEmail(p.email ?? ""); setGoal(p.goal); setLevel(p.level); setAvailableTime(p.availableTime); } }); }, []);
  const save = async () => { if (!name.trim()) { Alert.alert("Nome obrigatório", "Informe como você quer ser chamada."); return; } await saveUserProfile({ name: name.trim(), email: email.trim(), goal, level, availableTime, startDate: new Date().toISOString() }); router.back(); };
  return <ScreenContainer containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.close, { backgroundColor: colors.surfaceAlt }]}><IconSymbol name="chevron.left" size={22} color={colors.foreground} /></Pressable><Text style={[styles.title,{color:colors.foreground}]}>Editar perfil</Text><View style={styles.close}/></View><Text style={[styles.caption,{color:colors.muted}]}>Personalize a sua experiência no BARRIGAFIT.</Text><Field label="NOME" value={name} setValue={setName} colors={colors}/><Field label="E-MAIL" value={email} setValue={setEmail} colors={colors} email/><Selection label="OBJETIVO" values={["Definir abdômen","Perder peso","Fortalecer core","Melhorar postura"]} value={goal} onChange={setGoal} colors={colors}/><Selection label="NÍVEL" values={["Iniciante","Intermediário","Avançado"]} value={level} onChange={setLevel} colors={colors}/><Selection label="TEMPO DISPONÍVEL" values={["10 min","20 min","30 min","45 min"]} value={availableTime} onChange={setAvailableTime} colors={colors}/><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>Salvar alterações</Text></Pressable></ScrollView></ScreenContainer>;
}
function Field({label,value,setValue,colors,email}:{label:string;value:string;setValue:(v:string)=>void;colors:any;email?:boolean}){return <View style={styles.field}><Text style={[styles.label,{color:colors.muted}]}>{label}</Text><TextInput value={value} onChangeText={setValue} autoCapitalize={email?"none":"words"} keyboardType={email?"email-address":"default"} style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/></View>}
function Selection({label,values,value,onChange,colors}:{label:string;values:string[];value:string;onChange:(v:string)=>void;colors:any}){return <View style={styles.field}><Text style={[styles.label,{color:colors.muted}]}>{label}</Text><View style={styles.chips}>{values.map((v)=><Pressable key={v} onPress={()=>onChange(v)} style={[styles.chip,{borderColor:value===v?colors.primary:colors.border,backgroundColor:value===v?colors.primary+"22":colors.surfaceAlt}]}><Text style={{color:value===v?colors.primary:colors.foreground,fontSize:13,fontWeight:"700"}}>{v}</Text></Pressable>)}</View></View>}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:40},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},close:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center"},title:{fontSize:19,fontWeight:"800"},caption:{fontSize:14,lineHeight:20,marginTop:20,marginBottom:26},field:{marginBottom:22},label:{fontSize:10,fontWeight:"800",letterSpacing:1.2,marginBottom:8},input:{height:50,borderWidth:1,borderRadius:12,paddingHorizontal:14,fontSize:15,fontWeight:"600"},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderRadius:10,paddingHorizontal:12,paddingVertical:10},save:{height:52,marginTop:8,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#E91E8C"},saveText:{color:"#fff",fontSize:15,fontWeight:"800"}});
